### ISSUE TITLE
希望可以支持其他格式的文本文档

### ISSUE THREAD

**Issue by chinanoahli** [tastysugar/AssFontSubset#6]
工具是很好的工具，在epub制作上也能用，但是需要先把对应的文本转成ass格式，就不太方便

希望这个工具可以支持更多的文本文档格式

**Comment by tastysugar** [comment]
https://github.com/tastysugar/AssFontSubset/blob/7a7f41d0c978b1c49501bf56c07ded9526ee620d/AssFontSubset/MainWindow.xaml.cs#L446-L458

AssFontSubset 的底层使用的是 fonttools 中的 pyftsubset 来进行子集化。
AssFontSubset 只是把这个过程针对 ASS 格式进行了特化，自动化了在 ASS 文件中替换子集后的字体名的部分。（以及一些杂七杂八的小内容。）

如果有对其它格式进行子集化需求，推荐转换纯文本后使用 pyftsubset 进行子集化。

**Comment by chinanoahli** [comment]
感谢指引
