### ISSUE TITLE
在程序中加入更新提醒

### ISSUE THREAD

**Issue by Ming-Yue0** [tastysugar/AssFontSubset#9]
提醒用户更新 AssFontSubset

另：或许可以考虑加入 常见问题及解答 FAQ，出现内部错误时提醒用户尝试更新 `fonttools` 版本。

**Comment by tastysugar** [comment]
嗯，感觉不应该加在程序里
之后加个常见问题和解答

**Comment by Ming-Yue0** [comment]
> 嗯，感觉不应该加在程序里 之后加个常见问题和解答

可能我没说清楚，是程序里加入 AssFontSubset 的版本和更新提醒（链接到仓库地址就行）。FAQ 确实应该在仓库里写

**Comment by tastysugar** [comment]
AssFontSubset 是有更新提醒的，如果你的 AssFontSubset 的版本号低于 GitHub 中[这行](https://github.com/tastysugar/AssFontSubset/blob/7a7f41d0c978b1c49501bf56c07ded9526ee620d/AssFontSubset/Properties/AssemblyInfo.cs#L54)里的版本号，在运行程序时就会弹窗，在下图中这个窗口点 yes 就会弹到仓库地址。
![image](https://github.com/tastysugar/AssFontSubset/assets/37567389/7d34941b-1415-4a9e-940a-a75a8704801c)

**Comment by tastysugar** [comment]
常见问题及解答 FAQ 已更新。
